---
format:
  html:
    title: "Appendix: 女性団体の活動は福祉予算に影響を及ぼすのか：韓国・地方自治体の抗議イベントデータを用いた実証分析"
    author: Kazuhiro Terashita
    institute: Kyoto University
    date-modified: today
    link-external-newwindow: true
    #link-external-icon: true
    toc: true
    toc-depth: 5
    lang: ja
  docx: #形式を設定しなければならない
    #title: "Appendix"
    #date: today
    output-file: appendix.docx

format-links: 
  - html
  - text: PDF
    href: Appendix/Appendix.pdf
    icon: file-pdf

---

## 要約 / Abstruct

### 日本語

本稿は、韓国における基礎自治体のパネルデータを用いて、女性団体の活動が自治体の福祉予算に与える影響を明らかにした。先行研究は、女性団体をはじめとする「女性」の利益を代表するアクターが政治過程に参加することで、福祉の拡充がもたらされると論じてきた。この中で、女性団体はアウトサイダーとして、福祉拡充の世論形成に重要な役割を果たしつつ、時に労働団体や左派政党と連携して、政策起業家として福祉政策を主導してきたことが指摘されてきた。その一方で、先行研究では、女性団体と福祉政策の関係についてデータを用いた実証分析がほとんどなされてこなかった。そこで本稿では、韓国の基礎自治体の福祉予算の規定要因を分析し、女性団体の活動が福祉予算にいかなる影響を与えるのかを検討した。その際、機械学習を導入した抗議イベント分析を用いて、韓国語の新聞記事を分類することで、韓国各地の女性団体の活動に関する独自のデータを構築した。差の差法（DID）による分析の結果、女性団体の活動の有無が自治体の福祉予算に影響を与えるとは言えないが、進歩的な女性団体のみが抗議をしている場合か、女性・福祉に関するシグナルを発する抗議のみが観察される場合に、その2-3年後の人口一人当たり福祉予算が増加することが明らかになった。

### English

This paper uses panel data from local governments in Korea to examine the impact of the activities of women's organizations on the welfare budgets of local governments. Previous studies have argued that the participation of women's organizations and other women actors in the political process leads to welfare expansion. In this context, it has been pointed out that women's organizations, as outsiders, have played an important role in shaping public opinion in favor of welfare expansion, while at the same time acting as policy entrepreneurs, sometimes in cooperation with labor organizations and left-wing parties, in leading welfare policy. On the other hand, previous studies have rarely conducted empirical analyses using data on the relationship between women's organizations and welfare policy, and there has been a gap between theory and evidence. Therefore, this paper analyses the determinants of the welfare budgets of local governments in Korea and examines how the activities of women's groups affect welfare budgets. To do so, we constructed unique data on the activities of women's organizations in different regions of Korea by classifying newspaper articles in Korean using protest event analysis with the introduction of machine learning. Using the difference-in-differences (DID) method, we find that the presence or absence of women's organization activities does not affect a local government's welfare budget, but only when either only progressive women's organizations protest or only protests with signals about women and welfare are observed. 2-3 years later, welfare budgets per capita in the population were found to increase.

## Online Appendix (PDF)

<a href="Appendix/Appendix.pdf" class="btn btn-primary btn-sm" target="_blank" role="button"><i class="bi bi-window"></i>   Open PDF</a>

